name: CI

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Download urban areas dataset
        run: |
          mkdir -p data/places
          curl -L \
            https://api.figshare.com/v2/articles/13308773/download \
            -o data/places/13308773.zip

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore src/KenyaLocation.Api/KenyaLocation.Api.csproj

      - name: Build API
        run: dotnet build src/KenyaLocation.Api/KenyaLocation.Api.csproj --configuration Release --no-restore

      - name: Build API Docker image
        run: docker build -t kenya-location-api:ci ./src/KenyaLocation.Api

      - name: Build ingestion Docker image
        run: docker build -t kenya-location-ingestion:ci ./ingestion
